
build:
  version: "3.0"

cards:
  message: "Welcome to AbidiBank cards related local APIs "
  contactDetails:
    name: "Dragos Lech - Developer"
    email: "dragos@abidibank.com"
  onCallSupport:
      - (412) 419-3491
      - (915) 382-1932
