services:
  accounts:
    image: "youssefabidi929/accounts:s4"
    container_name: accounts-ms
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - youssefabidi929
  loans:
    image: "youssefabidi929/loans:s4"
    container_name: loans-ms
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - youssefabidi929
  cards:
    image: "youssefabidi929/cards:s4"
    container_name: cards-ms
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - youssefabidi929
networks:
  youssefabidi929:
    driver: "bridge"